### ISSUE TITLE
Found invalid rule names: subject-exclamation-mark

### ISSUE THREAD

**Issue by ocavue** [JulienKode/pull-request-name-linter-action#102]
After updated `@commitlint/config-conventional` to the latest version, I got this error in my workflow:

```
Run JulienKode/pull-request-name-linter-action@v0.2.0
Error: RangeError: Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
Error: Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
```

Downgrade `@commitlint/config-conventional` to `v12` fixes this issue.

**Comment by JulienKode** [comment]
Thanks for reporting this @ocavue @ciesielskico 

I think we need to update this package to use the latest version of commit lint

**Comment by JulienKode** [comment]
Thanks for reporting this @ocavue @ciesielskico

I think we need to update this package to use the latest version of commit lint

I've created: 
- 0.3.0 that use commitlint 12
- 0.4.0 that use commitlint 13

Maybe in the future the versioning of this package must match commitlint version to avoid confusion

**Comment by JulienKode** [comment]
Does it solve your issues ?

**Comment by ciesielskico** [comment]
Upgraded and pinned commitlint to v13 and the CI action to 0.4.0 and the error is gone, thanks.

Although I see that commitlint v16 has been released recently, any plans to support it as well?

**Comment by JulienKode** [comment]
Thanks for your feedback @ciesielskico, 

Yes we should support this, by doing a new release, 
Didn't had time to do it yet, 
But if you want to contribute feel free to open a pull request

**Comment by JulienKode** [comment]
@ciesielskico support of v16 is now done

**Comment by JulienKode** [comment]
@ocavue I close this issue, if you still have it, let me know, and reopen it, we can investigate on it if needed
