### ISSUE TITLE
example repo in the readme doesn't exist

### ISSUE THREAD

**Issue by jwr0** [JulienKode/pull-request-name-linter-action#200]
https://github.com/JulienKode/pull-request-name-linter-action-example is mentioned in the readme as an example repo which uses this action, but that repo 404's (doesn't exist, or is private).

**Comment by JulienKode** [comment]
@jwr0 

Thanks for noticing it, It's private, I'll put it in public

**Comment by airtonix** [comment]
still private

**Comment by JulienKode** [comment]
@airtonix @jwr0 it's now public

**Comment by JulienKode** [comment]
Feel free to re-open an issue if inside the example you want to add new things
